repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: end-of-file-fixer
        exclude: \.ret$
      - id: fix-byte-order-marker
        exclude: \.ret$
      - id: mixed-line-ending
        args: ["--fix", "lf"]
        exclude: \.ret$
      - id: trailing-whitespace
        exclude: \.ret$
      - id: check-yaml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        exclude: ^docs/source/_templates/
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
      - id: toml-sort-fix
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.3
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        require_serial: true
  - repo: https://github.com/crate-ci/typos
    rev: v1.24.1
    hooks:
      - id: typos
        args: ["--force-exclude"]
